---
- hosts: localhost

  vars:
    host_dict: "{{ host_dict }}"

  tasks:
    - name: Generating ssh config file (@ ~/.ssh/config)
      template:
        src: /home/stem-server/STEM-SLAM/server_files/controls/ansible/jinja/config.j2
        dest: /home/stem-server/STEM-SLAM/server_files/controls/ansible/config


...

# Run this with '-e "@hosts.yaml"'
